### ISSUE TITLE
[FEEDBACK] : Wrong text in exercise instruction (Exercises /02-qna.md)

### ISSUE THREAD

**Issue by callme-ocean** [MicrosoftLearning/mslearn-ai-language#22]
## Issue Summary

**Description:**
The text in step 4 in "Edit the knowledge base" section looks incorrect. While doing the exercise was not able to find the "What is Microsoft certification?" question.

**Expected Behavior:**
The text should be "What are Microsoft credentials?"

**Actual Behavior:**
Right now, the text is "What is Microsoft certification?" which is quite confusing.

## Steps to Reproduce

1. From exercise instruction perform all steps till the section "Add sources to the knowledge base".
2. While performing step 4 from the section "Edit the knowledge base" verify the environment with instructions https://microsoftlearning.github.io/mslearn-ai-language/Instructions/Exercises/02-qna.html

## Screenshots
![image](https://github.com/MicrosoftLearning/mslearn-ai-language/assets/79091096/c6d572c6-0cf9-484f-913e-eeba821b038c)

**Comment by ivorb** [comment]
fixed with 4034079, thanks for reporting
