### ISSUE TITLE
Typo in question on Knowledge Check

### ISSUE THREAD

**Issue by hammad93** [MicrosoftLearning/mslearn-ai-language#27]
I believe there's a small typo in the second question on the Knowledge Check of this section. 

> How might you determine ~~of~~ **if** this word

A screenshot for reference,
![image](https://github.com/MicrosoftLearning/mslearn-ai-language/assets/11673956/859d7a91-1fb0-48da-bb85-c30f695b6f90)

https://learn.microsoft.com/en-us/training/modules/analyze-text-ai-language/9-knowledge-check

**Comment by ivorb** [comment]
unrelated to the repo, but I've logged it for the module. thanks for reporting.
