### ISSUE TITLE
Lab 6 - Create a Question Answering Solution - Missing instructions

### ISSUE THREAD

**Issue by yashints** [MicrosoftLearning/mslearn-ai-language#30]
Hey team, 

Seems like the product team now mandates using an Azure Search instance when using custom question answering projects (might be true for other types too). We should add the instructions to create the search instance at the beginning of the project creation.

<img width="585" alt="image" src="https://github.com/MicrosoftLearning/mslearn-ai-language/assets/13609680/b9500e2e-5d23-4f4e-ba57-465b44d134ac">

**Comment by annav88** [comment]
hello Yas! could you add some repro steps and the step number where the issue happens, thank you!
