### ISSUE TITLE
Dependencies missing and VSC does not auto update

### ISSUE THREAD

**Issue by sarbjitsg** [MicrosoftLearning/mslearn-ai-language#32]
Recently started using the repo and notice each time i clone it to my local machine, i start seeing a lot of errors for the Microsoft C# extension. 

Here are just some. Literally every project for C# won't load. 

c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Newtonsoft.Json with version (>= 12.0.3)
  - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 9.0.1 ]
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.NETCore.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.WindowsDesktop.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.AspNetCore.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.NETCore.App.Host.win-x64. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.Extensions.Configuration.Json. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.NETCore.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.WindowsDesktop.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.AspNetCore.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.NETCore.App.Host.win-x64. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.Extensions.Configuration.Json. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.NETCore.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.WindowsDesktop.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.AspNetCore.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.NETCore.App.Host.win-x64. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.CognitiveServices.Speech. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.Extensions.Configuration.Json. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package System.Windows.Extensions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.NETCore.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.WindowsDesktop.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.AspNetCore.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:35 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\07-speech\C-Sharp\speaking-clock\speaking-clock.csproj: Unable to find package Microsoft.NETCore.App.Host.win-x64. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Info  - 11:27:45 AM] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:11.8654251
[Warn  - 11:27:46 AM] [LanguageServerProjectSystem] Project c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\06-translate-text\C-Sharp\text-translation\translate_text.csproj has unresolved dependencies
    Microsoft.Extensions.Configuration.Json-3.1.3
    Newtonsoft.Json-12.0.3
[Error - 11:27:46 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\06-translate-text\C-Sharp\text-translation\translate_text.csproj: Unable to find package Microsoft.Extensions.Configuration.Json. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:46 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\06-translate-text\C-Sharp\text-translation\translate_text.csproj: Unable to find package Newtonsoft.Json with version (>= 12.0.3)
  - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 9.0.1 ]
[Error - 11:27:46 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\06-translate-text\C-Sharp\text-translation\translate_text.csproj: Unable to find package Microsoft.NETCore.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:46 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\06-translate-text\C-Sharp\text-translation\translate_text.csproj: Unable to find package Microsoft.WindowsDesktop.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:46 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\06-translate-text\C-Sharp\text-translation\translate_text.csproj: Unable to find package Microsoft.AspNetCore.App.Ref. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Error - 11:27:46 AM] [LanguageServerProjectSystem] Failure while loading c:\Users\ssgil\melearnai\mslearn-ai-language\Labfiles\06-translate-text\C-Sharp\text-translation\translate_text.csproj: Unable to find package Microsoft.NETCore.App.Host.win-x64. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
[Info  - 11:27:47 AM] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:01.8937441

**Comment by ivorb** [comment]
hi @sarbjitsg it appears you're working on your local machine, which we cannot support given the variety of users using this learning content. You're welcome to use your Azure account on the hosted VMs available on Learn, or update the packages on your machine to match what's listed in these project files
