### ISSUE TITLE
Add Prebuild Geography.Location for the Location entity

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/mslearn-ai-language#43]
https://github.com/MicrosoftLearning/mslearn-ai-language/blob/34f75af101ea12675a6fd827b1f90ef53af10e81/Instructions/Exercises/03-language-understanding.md?plain=1#L163

Learner had to make the entity as prebuild Geography.Location for it to work. Just with the three examples given it was not consistent identifying it.

**Comment by unaihuete93** [comment]
The problem is that by using the machine learner option (with the given examples), the model was not able to detect location in many cases. It worked more consistently using the prebuild option ,as datetime does.

**Comment by ivorb** [comment]
added to backlog, closing this issue
