### ISSUE TITLE
URL missing https://learn.microsoft.com in https://raw.githubusercontent.com/MicrosoftLearning/mslearn-ai-language/main/Instructions/Exercises/03-language-understanding.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/mslearn-ai-language#45]
In Task 'Train and test the model', in the 'note' after step 5, the link is:

`[documentation](/azure/ai-services/language-service/conversational-language-understanding/concepts/evaluation-metrics)`

Appears to be missing a 'https://learn.microsoft.com', so correction should change it to:

`[documentation](https://learn.microsoft.com/azure/ai-services/language-service/conversational-language-understanding/concepts/evaluation-metrics)`

**Comment by ivorb** [comment]
fixed with 22020b5, thanks for reporting
