### ISSUE TITLE
Not able to create Custom Question Answering project and Language understanding project

### ISSUE THREAD

**Issue by azurearchitect786** [MicrosoftLearning/mslearn-ai-language#47]
![image](https://github.com/MicrosoftLearning/mslearn-ai-language/assets/56661030/479dd3f8-2774-47ed-beb8-75c29fdcb740)

Not able to create project due to server side issue.

No participant is able to create project during training hours.

**Comment by ivorb** [comment]
did you try this in a different region? East US region has been having issues for AI services, see if you have more success in a different region

**Comment by dishakamra** [comment]
Yes, using a different region is much better then using East US region. Thanks @ivorb for sharing this information :)
