### ISSUE TITLE
Exercise - Classify Text

### ISSUE THREAD

**Issue by peterparker123** [MicrosoftLearning/mslearn-ai-language#50]
https://microsoftlearning.github.io/mslearn-ai-language/Instructions/Exercises/04-text-classification.html
Facing issue when trying to create a project of Custom Text Classification. Find below the screen shot. Tried to deploy the project in the regions East US, East US 2 and West US 2, and encountered the same error.
![custom_text_issue](https://github.com/user-attachments/assets/85fa0654-3056-474d-bf26-bf914313c547)

**Comment by toinks989** [comment]
Getting the same issue on the next exercise, [Extract custom entities](https://github.com/MicrosoftLearning/mslearn-ai-language/blob/main/Instructions/Exercises/05-extract-custom-entities.md).

**Comment by ivorb** [comment]
Correct. To fix this, we add the role "Storage Blob Data Contributor" on the storage account for the user running the lab.

I'll update the instructions today to add the necessary steps, seems to be a new requirement for these labs

**Comment by peterparker123** [comment]
Thanks

**Comment by ivorb** [comment]
fixed with added tip
