### ISSUE TITLE
Lab 03 - Include Supported Regions 

### ISSUE THREAD

**Issue by sakkuru** [MicrosoftLearning/mslearn-ai-language#53]
https://github.com/MicrosoftLearning/mslearn-ai-language/blob/main/Instructions/Exercises/03-language-understanding.md

Currently, Conversational Language Understanding authoring is only available in specific regions. Shouldn't we include a list of supported regions (e.g., East US, Australia East) in the resource creation steps? Alternatively, we could provide a link to the list of supported regions.([Link](https://learn.microsoft.com/en-us/azure/ai-services/language-service/concepts/regional-support#conversational-language-understanding-and-orchestration-workflow))
This would help users avoid accidentally creating resources in unsupported regions.

**Comment by ivorb** [comment]
updated with PR #54
